In [26]:
import numpy as np
import pandas as pd

In [27]:
crime_df = pd.read_csv('../../범죄발생지_20260131175659.csv')
crime_df

,죄종별(1),죄종별(2),2024,2024.1,2024.2,2024.3,2024.4,2024.5,2024.6,2024.7,...,2024.90,2024.91,2024.92,2024.93,2024.94,2024.95,2024.96,2024.97,2024.98,2024.99
0,죄종별(1),죄종별(2),한국,한국,한국,한국,한국,한국,한국,한국,...,한국,한국,한국,한국,한국,한국,한국,한국,한국,한국
1,죄종별(1),죄종별(2),서울,서울,서울,서울,서울,서울,서울,서울,...,경기도,경기도,경기도,경기도,경기도,경기도,경기도,경기도,경기도,경기도
2,죄종별(1),죄종별(2),종로구,중구,용산구,성동구,광진구,동대문구,중랑구,성북구,...,안양시,양주시,여주시,오산시,용인시,의왕시,의정부시,이천시,파주시,평택시
3,강력범죄,살인기수,-,3,5,2,1,2,3,1,...,-,1,-,-,1,-,2,-,4,4
4,강력범죄,살인미수등,1,2,5,3,1,5,2,1,...,-,1,-,3,11,1,3,1,7,7
5,강력범죄,강도,5,5,4,2,6,4,2,1,...,-,4,-,1,1,-,2,1,6,6
6,강력범죄,강간,31,21,52,22,49,25,35,32,...,54,18,8,27,49,10,43,14,44,71
7,강력범죄,유사강간,6,7,9,3,9,9,5,8,...,3,5,2,1,11,-,10,4,6,14
8,강력범죄,강제추행,171,150,201,88,178,90,102,105,...,153,65,36,63,193,32,130,65,121,192
9,강력범죄,기타 강간/강제추행등,-,2,-,1,1,1,-,1,...,-,-,1,1,2,-,1,-,2,3
10,강력범죄,방화,9,8,6,7,7,8,10,5,...,13,3,2,8,16,-,10,6,6,10
11,폭력범죄,상해,110,96,103,74,89,88,117,67,...,148,63,34,98,194,29,140,76,135,226
12,폭력범죄,폭행,785,866,1187,504,705,869,840,648,...,979,593,196,634,1781,189,1324,478,1113,1940
13,폭력범죄,체포/감금,2,5,9,1,7,2,3,8,...,5,4,3,5,16,1,8,2,15,18
14,폭력범죄,협박,143,125,146,148,120,168,186,127,...,202,137,75,103,360,52,214,98,257,326
15,폭력범죄,약취/유인,1,-,5,1,2,2,5,1,...,2,-,-,4,4,-,3,1,1,4
16,폭력범죄,폭력행위등,23,37,47,17,22,27,41,17,...,25,24,4,26,73,11,33,21,46,87
17,폭력범죄,공갈,27,21,43,35,44,39,52,34,...,50,20,15,33,63,21,47,21,56,66
18,폭력범죄,손괴,269,228,401,253,314,267,335,247,...,397,234,109,354,754,60,360,263,435,751
19,지능범죄,직무유기,15,9,12,9,6,8,2,10,...,7,3,4,-,6,8,7,4,7,5
20,지능범죄,직권남용,24,15,13,3,10,13,8,6,...,11,-,1,5,15,10,13,4,10,17
21,지능범죄,증수뢰,3,3,2,1,5,2,-,4,...,2,-,-,1,8,2,-,1,-,3
22,지능범죄,통화,11,49,3,3,8,7,3,4,...,5,2,-,1,5,1,2,1,9,2
23,지능범죄,문서/인장,73,76,43,73,80,66,77,57,...,76,43,30,53,195,28,123,53,122,145
24,지능범죄,유가증권인지,2,4,-,-,1,1,-,-,...,1,-,-,-,2,-,-,-,1,-
25,지능범죄,사기,2440,1770,2170,2738,2150,2685,2809,2860,...,2936,1744,1070,1981,6964,883,3595,1918,4848,6937
26,지능범죄,횡령,766,823,594,555,694,617,468,412,...,750,250,85,309,988,81,656,200,776,654
27,지능범죄,배임,36,35,38,27,22,25,19,27,...,34,12,5,12,84,8,26,16,37,47
28,풍속범죄,성풍속범죄,129,99,128,123,169,125,126,125,...,178,62,30,89,308,36,199,87,216,239
29,풍속범죄,도박범죄,19,16,23,21,44,36,37,16,...,57,20,12,82,77,9,89,23,47,649

In [28]:
crime_df = crime_df.T
crime_df

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,...,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,풍속범죄,풍속범죄
죄종별(2),죄종별(2),죄종별(2),죄종별(2),살인기수,살인미수등,강도,강간,유사강간,강제추행,기타 강간/강제추행등,...,직권남용,증수뢰,통화,문서/인장,유가증권인지,사기,횡령,배임,성풍속범죄,도박범죄
2024,한국,서울,종로구,-,1,5,31,6,171,-,...,24,3,11,73,2,2440,766,36,129,19
2024.1,한국,서울,중구,3,2,5,21,7,150,2,...,15,3,49,76,4,1770,823,35,99,16
2024.2,한국,서울,용산구,5,5,4,52,9,201,-,...,13,2,3,43,-,2170,594,38,128,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024.95,한국,경기도,의왕시,-,1,-,10,-,32,-,...,10,2,1,28,-,883,81,8,36,9
2024.96,한국,경기도,의정부시,2,3,2,43,10,130,1,...,13,-,2,123,-,3595,656,26,199,89
2024.97,한국,경기도,이천시,-,1,1,14,4,65,-,...,4,1,1,53,-,1918,200,16,87,23
2024.98,한국,경기도,파주시,4,7,6,44,6,121,2,...,10,-,9,122,1,4848,776,37,216,47
2024.99,한국,경기도,평택시,4,7,6,71,14,192,3,...,17,3,2,145,-,6937,654,47,239,649

In [29]:
crime_df.columns = crime_df.iloc[0]

In [30]:
crime_df.head()

죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,...,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,풍속범죄,풍속범죄
죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,...,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,풍속범죄,풍속범죄
죄종별(2),죄종별(2),죄종별(2),죄종별(2),살인기수,살인미수등,강도,강간,유사강간,강제추행,기타 강간/강제추행등,...,직권남용,증수뢰,통화,문서/인장,유가증권인지,사기,횡령,배임,성풍속범죄,도박범죄
2024,한국,서울,종로구,-,1,5,31,6,171,-,...,24,3,11,73,2,2440,766,36,129,19
2024.1,한국,서울,중구,3,2,5,21,7,150,2,...,15,3,49,76,4,1770,823,35,99,16
2024.2,한국,서울,용산구,5,5,4,52,9,201,-,...,13,2,3,43,-,2170,594,38,128,23

In [31]:
crime_df = crime_df.drop(columns='지능범죄')

In [32]:
crime_df.info()
crime_df

<class 'pandas.core.frame.DataFrame'>
Index: 102 entries, 죄종별(1) to 2024.99
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   죄종별(1)  102 non-null    object
 1   죄종별(1)  102 non-null    object
 2   죄종별(1)  102 non-null    object
 3   강력범죄    102 non-null    object
 4   강력범죄    102 non-null    object
 5   강력범죄    102 non-null    object
 6   강력범죄    102 non-null    object
 7   강력범죄    102 non-null    object
 8   강력범죄    102 non-null    object
 9   강력범죄    102 non-null    object
 10  강력범죄    102 non-null    object
 11  폭력범죄    102 non-null    object
 12  폭력범죄    102 non-null    object
 13  폭력범죄    102 non-null    object
 14  폭력범죄    102 non-null    object
 15  폭력범죄    102 non-null    object
 16  폭력범죄    102 non-null    object
 17  폭력범죄    102 non-null    object
 18  폭력범죄    102 non-null    object
 19  풍속범죄    102 non-null    object
 20  풍속범죄    102 non-null    object
dtypes: object(21)
memory usage: 21.6+ KB

죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,...,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,풍속범죄,풍속범죄
죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,...,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,풍속범죄,풍속범죄
죄종별(2),죄종별(2),죄종별(2),죄종별(2),살인기수,살인미수등,강도,강간,유사강간,강제추행,기타 강간/강제추행등,...,상해,폭행,체포/감금,협박,약취/유인,폭력행위등,공갈,손괴,성풍속범죄,도박범죄
2024,한국,서울,종로구,-,1,5,31,6,171,-,...,110,785,2,143,1,23,27,269,129,19
2024.1,한국,서울,중구,3,2,5,21,7,150,2,...,96,866,5,125,-,37,21,228,99,16
2024.2,한국,서울,용산구,5,5,4,52,9,201,-,...,103,1187,9,146,5,47,43,401,128,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024.95,한국,경기도,의왕시,-,1,-,10,-,32,-,...,29,189,1,52,-,11,21,60,36,9
2024.96,한국,경기도,의정부시,2,3,2,43,10,130,1,...,140,1324,8,214,3,33,47,360,199,89
2024.97,한국,경기도,이천시,-,1,1,14,4,65,-,...,76,478,2,98,1,21,21,263,87,23
2024.98,한국,경기도,파주시,4,7,6,44,6,121,2,...,135,1113,15,257,1,46,56,435,216,47
2024.99,한국,경기도,평택시,4,7,6,71,14,192,3,...,226,1940,18,326,4,87,66,751,239,649

In [33]:
crime_df = crime_df.drop(columns='풍속범죄')

In [34]:
crime_df.head()

죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄
죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄
죄종별(2),죄종별(2),죄종별(2),죄종별(2),살인기수,살인미수등,강도,강간,유사강간,강제추행,기타 강간/강제추행등,방화,상해,폭행,체포/감금,협박,약취/유인,폭력행위등,공갈,손괴
2024,한국,서울,종로구,-,1,5,31,6,171,-,9,110,785,2,143,1,23,27,269
2024.1,한국,서울,중구,3,2,5,21,7,150,2,8,96,866,5,125,-,37,21,228
2024.2,한국,서울,용산구,5,5,4,52,9,201,-,6,103,1187,9,146,5,47,43,401

In [35]:
crime_df = crime_df.iloc[1:,:]

In [36]:
crime_df

죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄
죄종별(2),죄종별(2),죄종별(2),죄종별(2),살인기수,살인미수등,강도,강간,유사강간,강제추행,기타 강간/강제추행등,방화,상해,폭행,체포/감금,협박,약취/유인,폭력행위등,공갈,손괴
2024,한국,서울,종로구,-,1,5,31,6,171,-,9,110,785,2,143,1,23,27,269
2024.1,한국,서울,중구,3,2,5,21,7,150,2,8,96,866,5,125,-,37,21,228
2024.2,한국,서울,용산구,5,5,4,52,9,201,-,6,103,1187,9,146,5,47,43,401
2024.3,한국,서울,성동구,2,3,2,22,3,88,1,7,74,504,1,148,1,17,35,253
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024.95,한국,경기도,의왕시,-,1,-,10,-,32,-,-,29,189,1,52,-,11,21,60
2024.96,한국,경기도,의정부시,2,3,2,43,10,130,1,10,140,1324,8,214,3,33,47,360
2024.97,한국,경기도,이천시,-,1,1,14,4,65,-,6,76,478,2,98,1,21,21,263
2024.98,한국,경기도,파주시,4,7,6,44,6,121,2,6,135,1113,15,257,1,46,56,435
2024.99,한국,경기도,평택시,4,7,6,71,14,192,3,10,226,1940,18,326,4,87,66,751

In [37]:
crime_df = crime_df.iloc[2:,:]
crime_df

죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄
2024.1,한국,서울,중구,3,2,5,21,7,150,2,8,96,866,5,125,-,37,21,228
2024.2,한국,서울,용산구,5,5,4,52,9,201,-,6,103,1187,9,146,5,47,43,401
2024.3,한국,서울,성동구,2,3,2,22,3,88,1,7,74,504,1,148,1,17,35,253
2024.4,한국,서울,광진구,1,1,6,49,9,178,1,7,89,705,7,120,2,22,44,314
2024.5,한국,서울,동대문구,2,5,4,25,9,90,1,8,88,869,2,168,2,27,39,267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024.95,한국,경기도,의왕시,-,1,-,10,-,32,-,-,29,189,1,52,-,11,21,60
2024.96,한국,경기도,의정부시,2,3,2,43,10,130,1,10,140,1324,8,214,3,33,47,360
2024.97,한국,경기도,이천시,-,1,1,14,4,65,-,6,76,478,2,98,1,21,21,263
2024.98,한국,경기도,파주시,4,7,6,44,6,121,2,6,135,1113,15,257,1,46,56,435
2024.99,한국,경기도,평택시,4,7,6,71,14,192,3,10,226,1940,18,326,4,87,66,751

In [38]:
crime_df = crime_df.replace('-',0)
crime_df = crime_df.apply(pd.to_numeric, errors='ignore')
crime_df

C:\Users\USER\AppData\Local\Temp\ipykernel_29848\1782381427.py:2: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  crime_df = crime_df.apply(pd.to_numeric, errors='ignore')

죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄
2024.1,한국,서울,중구,3,2,5,21,7,150,2,8,96,866,5,125,0,37,21,228
2024.2,한국,서울,용산구,5,5,4,52,9,201,0,6,103,1187,9,146,5,47,43,401
2024.3,한국,서울,성동구,2,3,2,22,3,88,1,7,74,504,1,148,1,17,35,253
2024.4,한국,서울,광진구,1,1,6,49,9,178,1,7,89,705,7,120,2,22,44,314
2024.5,한국,서울,동대문구,2,5,4,25,9,90,1,8,88,869,2,168,2,27,39,267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024.95,한국,경기도,의왕시,0,1,0,10,0,32,0,0,29,189,1,52,0,11,21,60
2024.96,한국,경기도,의정부시,2,3,2,43,10,130,1,10,140,1324,8,214,3,33,47,360
2024.97,한국,경기도,이천시,0,1,1,14,4,65,0,6,76,478,2,98,1,21,21,263
2024.98,한국,경기도,파주시,4,7,6,44,6,121,2,6,135,1113,15,257,1,46,56,435
2024.99,한국,경기도,평택시,4,7,6,71,14,192,3,10,226,1940,18,326,4,87,66,751

In [39]:
crime_df.columns[:1]

Index(['죄종별(1)'], dtype='object', name='죄종별(1)')

In [40]:
cols = crime_df.columns.tolist()
cols[0] = '나라'
cols[1] = '행정구역'
cols[2] = '도시'
crime_df.columns = cols
crime_df

,나라,행정구역,도시,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄,폭력범죄
2024.1,한국,서울,중구,3,2,5,21,7,150,2,8,96,866,5,125,0,37,21,228
2024.2,한국,서울,용산구,5,5,4,52,9,201,0,6,103,1187,9,146,5,47,43,401
2024.3,한국,서울,성동구,2,3,2,22,3,88,1,7,74,504,1,148,1,17,35,253
2024.4,한국,서울,광진구,1,1,6,49,9,178,1,7,89,705,7,120,2,22,44,314
2024.5,한국,서울,동대문구,2,5,4,25,9,90,1,8,88,869,2,168,2,27,39,267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024.95,한국,경기도,의왕시,0,1,0,10,0,32,0,0,29,189,1,52,0,11,21,60
2024.96,한국,경기도,의정부시,2,3,2,43,10,130,1,10,140,1324,8,214,3,33,47,360
2024.97,한국,경기도,이천시,0,1,1,14,4,65,0,6,76,478,2,98,1,21,21,263
2024.98,한국,경기도,파주시,4,7,6,44,6,121,2,6,135,1113,15,257,1,46,56,435
2024.99,한국,경기도,평택시,4,7,6,71,14,192,3,10,226,1940,18,326,4,87,66,751

In [41]:
crime_df = crime_df.drop(columns='나라')

In [42]:
# 행정구역/도시 먼저 따로 보관
meta = crime_df[['행정구역', '도시']]

# 숫자 컬럼만 따로 떼서 숫자로 변환
nums = crime_df.drop(columns=['나라', '행정구역', '도시'], errors='ignore')
nums = nums.replace('-', 0)
nums = nums.apply(pd.to_numeric, errors='coerce').fillna(0)



# gpt...
# 같은 이름 컬럼(강력범죄, 폭력범죄 등) 합치기
nums = nums.T.groupby(level=0).sum().T

In [43]:
meta

        행정구역    도시
2024.1    서울    중구
2024.2    서울   용산구
2024.3    서울   성동구
2024.4    서울   광진구
2024.5    서울  동대문구
...      ...   ...
2024.95  경기도   의왕시
2024.96  경기도  의정부시
2024.97  경기도   이천시
2024.98  경기도   파주시
2024.99  경기도   평택시

[99 rows x 2 columns]

In [44]:
nums

         강력범죄  폭력범죄
2024.1    198  1378
2024.2    282  1941
2024.3    128  1033
2024.4    252  1303
2024.5    144  1462
...       ...   ...
2024.95    43   363
2024.96   201  2129
2024.97    91   960
2024.98   196  2058
2024.99   307  3418

[99 rows x 2 columns]

In [45]:
crime_df = pd.concat([meta, nums], axis=1)

In [46]:
crime_df = crime_df[['행정구역','도시','강력범죄','폭력범죄']]

In [47]:
crime_df = crime_df[['행정구역','도시','강력범죄','폭력범죄']].rename(columns={
    '행정구역': 'sido',
    '도시': 'sigungu',
    '강력범죄': 'crime',
    '폭력범죄': 'violence'
})

In [ ]:

#population에는 서울특별시, 부산광역시 처럼 돼 있는데
#지금 이 crime.json에는 서울, 부산 이렇게 돼 있음.
# 그래서 이름을 통일 시키려고하는 코드
sido_long_map = {
    "서울": "서울특별시",
    "부산": "부산광역시",
    "대구": "대구광역시",
    "인천": "인천광역시",
    "광주": "광주광역시",
    "대전": "대전광역시",
    "울산": "울산광역시",
    "세종": "세종특별자치시",
    "경기": "경기도",       # 혹시 '경기'로 들어온 값 대비
    "경기도": "경기도",
    "강원": "강원특별자치도",
    "충북": "충청북도",
    "충남": "충청남도",
    "전북": "전북특별자치도",
    "전남": "전라남도",
    "경북": "경상북도",
    "경남": "경상남도",
    "제주": "제주특별자치도",
}

# map : Series에 있는 각 값(서울, 부산, 대구…)을 딕셔너리로 하나씩 찾아서 바꿔주는 함수
# 값이 "서울"이면 → 딕셔너리에서 "서울" 키를 찾아 "서울특별시"로 바꿈
# 값이 "부산"이면 → "부산광역시"로 바꿈

#.fillna(crime_df["sido"]) : map()을 쓰다가 생긴 NaN을 “원래 값으로 복구”하는 역할
crime_df["sido"] = crime_df["sido"].map(sido_long_map).fillna(crime_df["sido"])

In [49]:
# 새로운 csv 파일로 저장. transform에서 json 형태로 바꾸기 위해서?
# 이건 좀 gpt 한테 도움 받았음 ㅎㅎ;;
crime_df.to_csv('crime_clean.csv', index=False, encoding='utf-8-sig')

In [50]:
# json 형태로 바꾸기
# 얘도 좀 gpt 한테 도움 받았음 ㅎㅎ;;
crime_df.to_json('crime.json', orient='records', force_ascii=False, indent=2)