In [116]:
import numpy as np
import pandas as pd

In [117]:
crime_df = pd.read_csv('../../범죄발생지_20260202223427.csv')
crime_df

,죄종별(1),죄종별(2),2024,2024.1,2024.2,2024.3,2024.4,2024.5,2024.6,2024.7,...,2024.237,2024.238,2024.239,2024.240,2024.241,2024.242,2024.243,2024.244,2024.245,2024.246
0,죄종별(1),죄종별(2),계,한국,한국,한국,한국,한국,한국,한국,...,한국,한국,한국,한국,한국,한국,한국,한국,한국,한국
1,죄종별(1),죄종별(2),소계,소계,서울,서울,서울,서울,서울,서울,...,경상남도,경상남도,경상남도,경상남도,경상남도,경상남도,경상남도,제주도,제주도,제주도
2,죄종별(1),죄종별(2),소계,소계,소계,종로구,중구,용산구,성동구,광진구,...,고성군,하동군,합천군,남해군,함양군,산청군,의령군,소계,서귀포시,제주시
3,강력범죄,살인기수,274,272,58,-,3,5,2,1,...,-,-,-,-,-,-,-,1,-,1
4,강력범죄,살인미수등,498,493,86,1,2,5,3,1,...,2,1,-,1,-,2,-,12,4,8
5,강력범죄,강도,457,451,86,5,5,4,2,6,...,-,1,-,-,-,-,-,11,5,6
6,강력범죄,강간,4777,4753,1124,31,21,52,22,49,...,6,2,-,1,1,1,2,98,21,77
7,강력범죄,유사강간,897,896,236,6,7,9,3,9,...,-,2,-,1,1,1,-,9,3,6
8,강력범죄,강제추행,15377,15346,4111,171,150,201,88,178,...,14,8,3,9,7,6,5,247,64,183
9,강력범죄,기타 강간/강제추행등,148,146,26,-,2,-,1,1,...,-,-,-,-,-,-,-,4,3,1
10,강력범죄,방화,1015,1015,180,9,8,6,7,7,...,1,3,2,2,-,-,2,19,4,15
11,폭력범죄,상해,19578,19551,2464,110,96,103,74,89,...,42,23,35,26,32,6,19,377,130,247
12,폭력범죄,폭행,115254,115209,22846,785,866,1187,504,705,...,59,78,59,47,33,48,52,2189,506,1683
13,폭력범죄,체포/감금,956,948,168,2,5,9,1,7,...,-,-,-,2,2,-,-,13,4,9
14,폭력범죄,협박,24190,24166,4382,143,125,146,148,120,...,19,20,15,7,22,9,18,515,139,376
15,폭력범죄,약취/유인,316,315,66,1,-,5,1,2,...,-,-,-,-,1,-,-,4,-,4
16,폭력범죄,폭력행위등,5713,5705,780,23,37,47,17,22,...,5,2,1,5,1,1,-,104,26,78
17,폭력범죄,공갈,6003,5986,1092,27,21,43,35,44,...,2,2,2,5,1,4,7,123,28,95
18,폭력범죄,손괴,47788,47786,7696,269,228,401,253,314,...,48,33,38,24,18,29,30,1206,397,809
19,지능범죄,직무유기,1077,1077,224,15,9,12,9,6,...,1,-,2,-,1,1,2,32,5,27
20,지능범죄,직권남용,1611,1611,280,24,15,13,3,10,...,-,-,-,1,1,-,2,94,41,53
21,지능범죄,증수뢰,307,307,77,3,3,2,1,5,...,1,-,1,-,1,-,-,6,1,5
22,지능범죄,통화,489,482,185,11,49,3,3,8,...,-,-,-,-,-,-,-,7,1,6
23,지능범죄,문서/인장,12746,12714,2395,73,76,43,73,80,...,17,7,6,9,9,12,8,185,44,141
24,지능범죄,유가증권인지,59,59,28,2,4,-,-,1,...,-,-,-,-,-,-,-,-,-,-
25,지능범죄,사기,421421,420616,81265,2440,1770,2170,2738,2150,...,410,271,195,243,192,124,179,8511,1950,6561
26,지능범죄,횡령,63601,63536,16436,766,823,594,555,694,...,24,21,30,28,18,16,19,1032,235,797
27,지능범죄,배임,3897,3882,983,36,35,38,27,22,...,3,1,3,2,2,1,5,71,20,51
28,풍속범죄,성풍속범죄,18737,18681,4161,129,99,128,123,169,...,4,9,6,3,5,1,4,266,54,212
29,풍속범죄,도박범죄,8865,8816,1019,19,16,23,21,44,...,3,3,3,1,5,1,5,138,29,109

In [118]:
crime_df = crime_df.T
crime_df

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,...,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,풍속범죄,풍속범죄
죄종별(2),죄종별(2),죄종별(2),죄종별(2),살인기수,살인미수등,강도,강간,유사강간,강제추행,기타 강간/강제추행등,...,직권남용,증수뢰,통화,문서/인장,유가증권인지,사기,횡령,배임,성풍속범죄,도박범죄
2024,계,소계,소계,274,498,457,4777,897,15377,148,...,1611,307,489,12746,59,421421,63601,3897,18737,8865
2024.1,한국,소계,소계,272,493,451,4753,896,15346,146,...,1611,307,482,12714,59,420616,63536,3882,18681,8816
2024.2,한국,서울,소계,58,86,86,1124,236,4111,26,...,280,77,185,2395,28,81265,16436,983,4161,1019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024.242,한국,경상남도,산청군,-,2,-,1,1,6,-,...,-,-,-,12,-,124,16,1,1,1
2024.243,한국,경상남도,의령군,-,-,-,2,-,5,-,...,2,-,-,8,-,179,19,5,4,5
2024.244,한국,제주도,소계,1,12,11,98,9,247,4,...,94,6,7,185,-,8511,1032,71,266,138
2024.245,한국,제주도,서귀포시,-,4,5,21,3,64,3,...,41,1,1,44,-,1950,235,20,54,29
2024.246,한국,제주도,제주시,1,8,6,77,6,183,1,...,53,5,6,141,-,6561,797,51,212,109

In [119]:
crime_df.columns = crime_df.iloc[0]

In [120]:
crime_df.head()

죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,...,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,풍속범죄,풍속범죄
죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,...,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,풍속범죄,풍속범죄
죄종별(2),죄종별(2),죄종별(2),죄종별(2),살인기수,살인미수등,강도,강간,유사강간,강제추행,기타 강간/강제추행등,...,직권남용,증수뢰,통화,문서/인장,유가증권인지,사기,횡령,배임,성풍속범죄,도박범죄
2024,계,소계,소계,274,498,457,4777,897,15377,148,...,1611,307,489,12746,59,421421,63601,3897,18737,8865
2024.1,한국,소계,소계,272,493,451,4753,896,15346,146,...,1611,307,482,12714,59,420616,63536,3882,18681,8816
2024.2,한국,서울,소계,58,86,86,1124,236,4111,26,...,280,77,185,2395,28,81265,16436,983,4161,1019

In [121]:
crime_df.info()
crime_df

<class 'pandas.core.frame.DataFrame'>
Index: 249 entries, 죄종별(1) to 2024.246
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   죄종별(1)  249 non-null    object
 1   죄종별(1)  249 non-null    object
 2   죄종별(1)  249 non-null    object
 3   강력범죄    249 non-null    object
 4   강력범죄    249 non-null    object
 5   강력범죄    249 non-null    object
 6   강력범죄    249 non-null    object
 7   강력범죄    249 non-null    object
 8   강력범죄    249 non-null    object
 9   강력범죄    249 non-null    object
 10  강력범죄    249 non-null    object
 11  폭력범죄    249 non-null    object
 12  폭력범죄    249 non-null    object
 13  폭력범죄    249 non-null    object
 14  폭력범죄    249 non-null    object
 15  폭력범죄    249 non-null    object
 16  폭력범죄    249 non-null    object
 17  폭력범죄    249 non-null    object
 18  폭력범죄    249 non-null    object
 19  지능범죄    249 non-null    object
 20  지능범죄    249 non-null    object
 21  지능범죄    249 non-null    object
 22  지능범죄    249 non-null    object
 23  지능범죄    249 non-null    object
 24  지능범죄    249 non-null    object
 25  지능범죄    249 non-null    object
 26  지능범죄    249 non-null    object
 27  지능범죄    249 non-null    object
 28  풍속범죄    249 non-null    object
 29  풍속범죄    249 non-null    object
dtypes: object(30)
memory usage: 68.4+ KB

죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,...,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,풍속범죄,풍속범죄
죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,...,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,풍속범죄,풍속범죄
죄종별(2),죄종별(2),죄종별(2),죄종별(2),살인기수,살인미수등,강도,강간,유사강간,강제추행,기타 강간/강제추행등,...,직권남용,증수뢰,통화,문서/인장,유가증권인지,사기,횡령,배임,성풍속범죄,도박범죄
2024,계,소계,소계,274,498,457,4777,897,15377,148,...,1611,307,489,12746,59,421421,63601,3897,18737,8865
2024.1,한국,소계,소계,272,493,451,4753,896,15346,146,...,1611,307,482,12714,59,420616,63536,3882,18681,8816
2024.2,한국,서울,소계,58,86,86,1124,236,4111,26,...,280,77,185,2395,28,81265,16436,983,4161,1019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024.242,한국,경상남도,산청군,-,2,-,1,1,6,-,...,-,-,-,12,-,124,16,1,1,1
2024.243,한국,경상남도,의령군,-,-,-,2,-,5,-,...,2,-,-,8,-,179,19,5,4,5
2024.244,한국,제주도,소계,1,12,11,98,9,247,4,...,94,6,7,185,-,8511,1032,71,266,138
2024.245,한국,제주도,서귀포시,-,4,5,21,3,64,3,...,41,1,1,44,-,1950,235,20,54,29
2024.246,한국,제주도,제주시,1,8,6,77,6,183,1,...,53,5,6,141,-,6561,797,51,212,109

In [122]:
crime_df.head()

죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,...,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,풍속범죄,풍속범죄
죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,...,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,풍속범죄,풍속범죄
죄종별(2),죄종별(2),죄종별(2),죄종별(2),살인기수,살인미수등,강도,강간,유사강간,강제추행,기타 강간/강제추행등,...,직권남용,증수뢰,통화,문서/인장,유가증권인지,사기,횡령,배임,성풍속범죄,도박범죄
2024,계,소계,소계,274,498,457,4777,897,15377,148,...,1611,307,489,12746,59,421421,63601,3897,18737,8865
2024.1,한국,소계,소계,272,493,451,4753,896,15346,146,...,1611,307,482,12714,59,420616,63536,3882,18681,8816
2024.2,한국,서울,소계,58,86,86,1124,236,4111,26,...,280,77,185,2395,28,81265,16436,983,4161,1019

In [123]:
crime_df = crime_df.iloc[1:,:]

In [124]:
crime_df

죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,...,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,풍속범죄,풍속범죄
죄종별(2),죄종별(2),죄종별(2),죄종별(2),살인기수,살인미수등,강도,강간,유사강간,강제추행,기타 강간/강제추행등,...,직권남용,증수뢰,통화,문서/인장,유가증권인지,사기,횡령,배임,성풍속범죄,도박범죄
2024,계,소계,소계,274,498,457,4777,897,15377,148,...,1611,307,489,12746,59,421421,63601,3897,18737,8865
2024.1,한국,소계,소계,272,493,451,4753,896,15346,146,...,1611,307,482,12714,59,420616,63536,3882,18681,8816
2024.2,한국,서울,소계,58,86,86,1124,236,4111,26,...,280,77,185,2395,28,81265,16436,983,4161,1019
2024.3,한국,서울,종로구,-,1,5,31,6,171,-,...,24,3,11,73,2,2440,766,36,129,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024.242,한국,경상남도,산청군,-,2,-,1,1,6,-,...,-,-,-,12,-,124,16,1,1,1
2024.243,한국,경상남도,의령군,-,-,-,2,-,5,-,...,2,-,-,8,-,179,19,5,4,5
2024.244,한국,제주도,소계,1,12,11,98,9,247,4,...,94,6,7,185,-,8511,1032,71,266,138
2024.245,한국,제주도,서귀포시,-,4,5,21,3,64,3,...,41,1,1,44,-,1950,235,20,54,29
2024.246,한국,제주도,제주시,1,8,6,77,6,183,1,...,53,5,6,141,-,6561,797,51,212,109

In [125]:
crime_df = crime_df.iloc[2:,:]
crime_df

죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,...,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,풍속범죄,풍속범죄
2024.1,한국,소계,소계,272,493,451,4753,896,15346,146,...,1611,307,482,12714,59,420616,63536,3882,18681,8816
2024.2,한국,서울,소계,58,86,86,1124,236,4111,26,...,280,77,185,2395,28,81265,16436,983,4161,1019
2024.3,한국,서울,종로구,-,1,5,31,6,171,-,...,24,3,11,73,2,2440,766,36,129,19
2024.4,한국,서울,중구,3,2,5,21,7,150,2,...,15,3,49,76,4,1770,823,35,99,16
2024.5,한국,서울,용산구,5,5,4,52,9,201,-,...,13,2,3,43,-,2170,594,38,128,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024.242,한국,경상남도,산청군,-,2,-,1,1,6,-,...,-,-,-,12,-,124,16,1,1,1
2024.243,한국,경상남도,의령군,-,-,-,2,-,5,-,...,2,-,-,8,-,179,19,5,4,5
2024.244,한국,제주도,소계,1,12,11,98,9,247,4,...,94,6,7,185,-,8511,1032,71,266,138
2024.245,한국,제주도,서귀포시,-,4,5,21,3,64,3,...,41,1,1,44,-,1950,235,20,54,29
2024.246,한국,제주도,제주시,1,8,6,77,6,183,1,...,53,5,6,141,-,6561,797,51,212,109

In [126]:
crime_df = crime_df.replace('-',0)
crime_df = crime_df.apply(pd.to_numeric, errors='ignore')
crime_df

/var/folders/t3/3hs6sjnx4152hbtrj0c_f_sw0000gn/T/ipykernel_85561/1782381427.py:2: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  crime_df = crime_df.apply(pd.to_numeric, errors='ignore')

죄종별(1),죄종별(1),죄종별(1),죄종별(1),강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,...,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,풍속범죄,풍속범죄
2024.1,한국,소계,소계,272,493,451,4753,896,15346,146,...,1611,307,482,12714,59,420616,63536,3882,18681,8816
2024.2,한국,서울,소계,58,86,86,1124,236,4111,26,...,280,77,185,2395,28,81265,16436,983,4161,1019
2024.3,한국,서울,종로구,0,1,5,31,6,171,0,...,24,3,11,73,2,2440,766,36,129,19
2024.4,한국,서울,중구,3,2,5,21,7,150,2,...,15,3,49,76,4,1770,823,35,99,16
2024.5,한국,서울,용산구,5,5,4,52,9,201,0,...,13,2,3,43,0,2170,594,38,128,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024.242,한국,경상남도,산청군,0,2,0,1,1,6,0,...,0,0,0,12,0,124,16,1,1,1
2024.243,한국,경상남도,의령군,0,0,0,2,0,5,0,...,2,0,0,8,0,179,19,5,4,5
2024.244,한국,제주도,소계,1,12,11,98,9,247,4,...,94,6,7,185,0,8511,1032,71,266,138
2024.245,한국,제주도,서귀포시,0,4,5,21,3,64,3,...,41,1,1,44,0,1950,235,20,54,29
2024.246,한국,제주도,제주시,1,8,6,77,6,183,1,...,53,5,6,141,0,6561,797,51,212,109

In [127]:
crime_df.columns[:1]

Index(['죄종별(1)'], dtype='object', name='죄종별(1)')

In [128]:
cols = crime_df.columns.tolist()
cols[0] = '나라'
cols[1] = '행정구역'
cols[2] = '도시'
crime_df.columns = cols
crime_df

,나라,행정구역,도시,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,강력범죄,...,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,지능범죄,풍속범죄,풍속범죄
2024.1,한국,소계,소계,272,493,451,4753,896,15346,146,...,1611,307,482,12714,59,420616,63536,3882,18681,8816
2024.2,한국,서울,소계,58,86,86,1124,236,4111,26,...,280,77,185,2395,28,81265,16436,983,4161,1019
2024.3,한국,서울,종로구,0,1,5,31,6,171,0,...,24,3,11,73,2,2440,766,36,129,19
2024.4,한국,서울,중구,3,2,5,21,7,150,2,...,15,3,49,76,4,1770,823,35,99,16
2024.5,한국,서울,용산구,5,5,4,52,9,201,0,...,13,2,3,43,0,2170,594,38,128,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024.242,한국,경상남도,산청군,0,2,0,1,1,6,0,...,0,0,0,12,0,124,16,1,1,1
2024.243,한국,경상남도,의령군,0,0,0,2,0,5,0,...,2,0,0,8,0,179,19,5,4,5
2024.244,한국,제주도,소계,1,12,11,98,9,247,4,...,94,6,7,185,0,8511,1032,71,266,138
2024.245,한국,제주도,서귀포시,0,4,5,21,3,64,3,...,41,1,1,44,0,1950,235,20,54,29
2024.246,한국,제주도,제주시,1,8,6,77,6,183,1,...,53,5,6,141,0,6561,797,51,212,109

In [129]:
crime_df = crime_df.drop(columns='나라')

In [130]:
# 행정구역/도시 먼저 따로 보관
meta = crime_df[['행정구역', '도시']]

# 숫자 컬럼만 따로 떼서 숫자로 변환
nums = crime_df.drop(columns=['나라', '행정구역', '도시'], errors='ignore')
nums = nums.replace('-', 0)
nums = nums.apply(pd.to_numeric, errors='coerce').fillna(0)



# gpt...
# 같은 이름 컬럼(강력범죄, 폭력범죄 등) 합치기
nums = nums.T.groupby(level=0).sum().T

In [131]:
meta

          행정구역    도시
2024.1      소계    소계
2024.2      서울    소계
2024.3      서울   종로구
2024.4      서울    중구
2024.5      서울   용산구
...        ...   ...
2024.242  경상남도   산청군
2024.243  경상남도   의령군
2024.244   제주도    소계
2024.245   제주도  서귀포시
2024.246   제주도   제주시

[246 rows x 2 columns]

In [132]:
nums

           강력범죄    지능범죄    폭력범죄   풍속범죄
2024.1    23372  504284  219666  27497
2024.2     5907  101873   39494   5180
2024.3      223    3370    1360    148
2024.4      198    2784    1378    115
2024.5      282    2875    1941    151
...         ...     ...     ...    ...
2024.242     10     154      97      2
2024.243      9     215     126      9
2024.244    401    9938    4531    404
2024.245    104    2297    1230     83
2024.246    297    7641    3301    321

[246 rows x 4 columns]

In [133]:
crime_df = pd.concat([meta, nums], axis=1)

In [134]:
crime_df = crime_df[['행정구역','도시','강력범죄','폭력범죄','지능범죄','풍속범죄']]

In [135]:
crime_df['crime'] = crime_df[['강력범죄','폭력범죄','지능범죄','풍속범죄']].sum(axis=1)
crime_df

          행정구역    도시   강력범죄    폭력범죄    지능범죄   풍속범죄   crime
2024.1      소계    소계  23372  219666  504284  27497  774819
2024.2      서울    소계   5907   39494  101873   5180  152454
2024.3      서울   종로구    223    1360    3370    148    5101
2024.4      서울    중구    198    1378    2784    115    4475
2024.5      서울   용산구    282    1941    2875    151    5249
...        ...   ...    ...     ...     ...    ...     ...
2024.242  경상남도   산청군     10      97     154      2     263
2024.243  경상남도   의령군      9     126     215      9     359
2024.244   제주도    소계    401    4531    9938    404   15274
2024.245   제주도  서귀포시    104    1230    2297     83    3714
2024.246   제주도   제주시    297    3301    7641    321   11560

[246 rows x 7 columns]

In [136]:
crime_df['violence'] = crime_df[['강력범죄','폭력범죄']].sum(axis=1)
crime_df

          행정구역    도시   강력범죄    폭력범죄    지능범죄   풍속범죄   crime  violence
2024.1      소계    소계  23372  219666  504284  27497  774819    243038
2024.2      서울    소계   5907   39494  101873   5180  152454     45401
2024.3      서울   종로구    223    1360    3370    148    5101      1583
2024.4      서울    중구    198    1378    2784    115    4475      1576
2024.5      서울   용산구    282    1941    2875    151    5249      2223
...        ...   ...    ...     ...     ...    ...     ...       ...
2024.242  경상남도   산청군     10      97     154      2     263       107
2024.243  경상남도   의령군      9     126     215      9     359       135
2024.244   제주도    소계    401    4531    9938    404   15274      4932
2024.245   제주도  서귀포시    104    1230    2297     83    3714      1334
2024.246   제주도   제주시    297    3301    7641    321   11560      3598

[246 rows x 8 columns]

In [137]:
crime_df = crime_df.drop(columns=['강력범죄','폭력범죄','지능범죄','풍속범죄'],errors='ignore')

In [138]:
crime_df

          행정구역    도시   crime  violence
2024.1      소계    소계  774819    243038
2024.2      서울    소계  152454     45401
2024.3      서울   종로구    5101      1583
2024.4      서울    중구    4475      1576
2024.5      서울   용산구    5249      2223
...        ...   ...     ...       ...
2024.242  경상남도   산청군     263       107
2024.243  경상남도   의령군     359       135
2024.244   제주도    소계   15274      4932
2024.245   제주도  서귀포시    3714      1334
2024.246   제주도   제주시   11560      3598

[246 rows x 4 columns]

In [139]:
crime_df = crime_df[['행정구역','도시','crime','violence']].rename(columns={
    '행정구역': 'sido',
    '도시': 'sigungu',
    # '강력범죄': 'crime',# crime <- 범죄 총계
    # '폭력범죄': 'violence' <- 강력 + 폭력
    # 강력범죄 -> violence로
    # crime -> 총계
})

In [140]:
crime_df

          sido sigungu   crime  violence
2024.1      소계      소계  774819    243038
2024.2      서울      소계  152454     45401
2024.3      서울     종로구    5101      1583
2024.4      서울      중구    4475      1576
2024.5      서울     용산구    5249      2223
...        ...     ...     ...       ...
2024.242  경상남도     산청군     263       107
2024.243  경상남도     의령군     359       135
2024.244   제주도      소계   15274      4932
2024.245   제주도    서귀포시    3714      1334
2024.246   제주도     제주시   11560      3598

[246 rows x 4 columns]

In [141]:

#population에는 서울특별시, 부산광역시 처럼 돼 있는데
#지금 이 crime.json에는 서울, 부산 이렇게 돼 있음.
# 그래서 이름을 통일 시키려고하는 코드
sido_long_map = {
    "서울": "서울특별시",
    "부산": "부산광역시",
    "대구": "대구광역시",
    "인천": "인천광역시",
    "광주": "광주광역시",
    "대전": "대전광역시",
    "울산": "울산광역시",
    "세종": "세종특별자치시",
    "경기": "경기도",       # 혹시 '경기'로 들어온 값 대비
    "경기도": "경기도",
    "강원": "강원특별자치도",
    "충북": "충청북도",
    "충남": "충청남도",
    "전북": "전북특별자치도",
    "전남": "전라남도",
    "경북": "경상북도",
    "경남": "경상남도",
    "제주": "제주특별자치도",
}

# map : Series에 있는 각 값(서울, 부산, 대구…)을 딕셔너리로 하나씩 찾아서 바꿔주는 함수
# 값이 "서울"이면 → 딕셔너리에서 "서울" 키를 찾아 "서울특별시"로 바꿈
# 값이 "부산"이면 → "부산광역시"로 바꿈

#.fillna(crime_df["sido"]) : map()을 쓰다가 생긴 NaN을 “원래 값으로 복구”하는 역할
crime_df["sido"] = crime_df["sido"].map(sido_long_map).fillna(crime_df["sido"])

In [142]:
# 새로운 csv 파일로 저장. transform에서 json 형태로 바꾸기 위해서?
# 이건 좀 gpt 한테 도움 받았음 ㅎㅎ;;

import os
os.makedirs('data', exist_ok=True)
crime_df.to_csv('data/crime_clean.csv', index=False, encoding='utf-8-sig')

In [143]:
# json 형태로 바꾸기
# 얘도 좀 gpt 한테 도움 받았음 ㅎㅎ;;
crime_df.to_json('data/crime.json', orient='records', force_ascii=False, indent=2)