In [11]:
import numpy as np
import pandas as pd

In [12]:
population_df = pd.read_csv('../../도시지역_인구현황_시군구__20260203013750.csv')
population_df

,소재지(시군구)별(1),소재지(시군구)별(2),2024,2024.1,2024.2,2024.3,2024.4,2024.5,2024.6
0,소재지(시군구)별(1),소재지(시군구)별(2),전체인구(A) (명),용도지역기준 (명),용도지역기준 (명),행정구역기준 (명),행정구역기준 (명),도시지역 인구비율 (%),도시지역 인구비율 (%)
1,소재지(시군구)별(1),소재지(시군구)별(2),소계,도시인구(B),비도시인구(C=A-B),도시인구(D),농촌인구(E=A-D),용도지역 인구기준(B/A*100),행정구역 인구기준(D/A*100)
2,전국,소계,51217221,47146348,4070873,46827382,4389839,92.05,91.43
3,서울특별시,소계,9331828,9331828,0,9331828,0,100.00,100.00
4,서울특별시,종로구,138336,138336,0,138336,0,100.00,100.00
...,...,...,...,...,...,...,...,...,...
244,경상남도,거창군,59588,39685,19903,39699,19889,66.60,66.62
245,경상남도,합천군,40225,23695,16530,10649,29576,58.91,26.47
246,제주특별자치도,소계,670368,606672,63696,632544,37824,90.50,94.36
247,제주특별자치도,제주시,488348,449280,39068,475661,12687,92.00,97.40
248,제주특별자치도,서귀포시,182020,157392,24628,156883,25137,86.47,86.19

In [13]:
population_df = population_df.drop(columns=['2024.1','2024.2','2024.3','2024.4','2024.5','2024.6'])

In [14]:
population_df

     소재지(시군구)별(1)  소재지(시군구)별(2)         2024
0    소재지(시군구)별(1)  소재지(시군구)별(2)  전체인구(A) (명)
1    소재지(시군구)별(1)  소재지(시군구)별(2)           소계
2              전국            소계     51217221
3           서울특별시            소계      9331828
4           서울특별시           종로구       138336
..            ...           ...          ...
244          경상남도           거창군        59588
245          경상남도           합천군        40225
246       제주특별자치도            소계       670368
247       제주특별자치도           제주시       488348
248       제주특별자치도          서귀포시       182020

[249 rows x 3 columns]

In [15]:
population_df = population_df.iloc[2:].reset_index(drop=True)

In [16]:
population_df

    소재지(시군구)별(1) 소재지(시군구)별(2)      2024
0             전국           소계  51217221
1          서울특별시           소계   9331828
2          서울특별시          종로구    138336
3          서울특별시           중구    120544
4          서울특별시          용산구    203854
..           ...          ...       ...
242         경상남도          거창군     59588
243         경상남도          합천군     40225
244      제주특별자치도           소계    670368
245      제주특별자치도          제주시    488348
246      제주특별자치도         서귀포시    182020

[247 rows x 3 columns]

In [17]:
population_df= population_df.rename(columns={'소재지(시군구)별(1)' :'sido',
                              '소재지(시군구)별(2)' : 'sigungu',
                              '2024' : 'population'
                              })

In [18]:
# population_df = population_df.set_index('sido')

In [19]:
import os
os.makedirs('data', exist_ok=True)
population_df.to_csv('data/population_clean.csv', index=False, encoding='utf-8-sig')

In [20]:
# features/population/data/ 에 저장
population_df.to_json('data/population.json', orient='records', force_ascii=False, indent=2)